repos:
  # Ruff linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  # Additional useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Prevent large files from being committed
      - id: check-added-large-files
        args: ['--maxkb=1000']
      # Check for files that would conflict on case-insensitive filesystems
      - id: check-case-conflict
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Check YAML files for syntax errors
      - id: check-yaml
      # Check TOML files for syntax errors
      - id: check-toml
      # Check JSON files for syntax errors
      - id: check-json
      # Ensure files end with a newline
      - id: end-of-file-fixer
      # Remove trailing whitespace
      - id: trailing-whitespace
      # Check for common mistakes in Python files
      - id: check-ast
      # Sort requirements files
      - id: requirements-txt-fixer

  # Security checks (disabled for now - can re-enable after fixing issues)
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.7
  #   hooks:
  #     - id: bandit
  #       args: ["-ll", "-x", "tests/"]

  # Type checking with mypy (disabled for now - can re-enable after fixing types)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.11.2
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-requests]
  #       args: [--ignore-missing-imports, --no-strict-optional, --allow-untyped-defs]
  #       files: ^fitlog/
